plugin:
    has_options: true                                                   #the plugin has option
    icon: res_simu.png
    resources:
        - class: CPASimUSante\SimuResourceBundle\Entity\SimuResource    #the resource main entity
          name: cpasimusante_simuresource                               # the resource name
          is_exportable: true
          is_browsable: true
          icon: res_simu.png
          actions:
              - name: dostuff
                menu_name: dostuff
              - name: doinmodal
                menu_name: doinmodal
                is_form: true                                           #mandatory to have a modal
              - name: updatesimuresourceinpage
                menu_name: updatesimuresourceinpage
              - name: testlog
                menu_name: testlog
              - name: testupload
                menu_name: testupload
          activity_rules:                                               #to be added in claro_activity_rule_action 
              - action: resource-read
              - action: resource-cpasimusante_simuresource-simuresource_edit