plugin:
    has_options: true                                                   #the plugin has option
    icon: res_simu.png
    resources:
        - class: CPASimUSante\SimuResourceBundle\Entity\SimuResource    #the resource main entity
          name: cpasimusante_simuresource                               # the resource name
          is_exportable: true
          is_browsable: true
          icon: res_simu.png
          actions:
            - name: docustomstuff
              menu_name: docustomstuff
#              is_form: true