plugin:
    has_options: true
    icon: res_simu.png
    resources:
        - class: CPASimUSante\SimuResourceBundle\Entity\SimuResource    #the resource main entity
          name: cpasimusante_simuresource                               # the resource name
          is_exportable: true
          is_browsable: true
          icon: res_simu.png
          actions:
            - name: cpasimusante_simuresource
            - menu_name: cpasimusante_simuresource_menu
              is_form: true