services:
    cpasimusante.listener.simuresource.notification_listener:
        class: CPASimUSante\SimuResourceBundle\Listener\NotificationListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: create_notification_item_resource-cpasimusante_simuresource-simuresource_edit,    method: onCreateNotificationItem }
#format for event: create_notification_item_%actionname%
#listener to display in notification list